# Generated by Django 6.0.1 on 2026-01-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
    ]
