# Generated by Django 6.0.1 on 2026-02-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_transactions_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='type',
        ),
    ]
